---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2 # arm64 -> https://github.com/rook/rook/issues/14502
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "nvme0n1p3"
    devices:
      - name: "nvme0n1p3"
    config:
      osdsPerDevice: "1"
      encryptedDevice: "false"
      osdStore: bluestore
      storeType: raw
  resources:
    mon:
      requests:
        cpu: 250m
        memory: 512Mi
    mgr:
      requests:
        cpu: 250m
        memory: 512Mi
    osd:
      requests:
        cpu: 250m
        memory: 1Gi
