repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: external-dns
    namespace: external-dns
    createNamespace: true
    chart: "external-dns/external-dns"
    version: 1.22.0
    wait: true
    atomic: true
    values:
      - values/external-dns.yaml.gotmpl
