repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: nginx-ingress
    namespace: r2dlan-system
    chart: ingress-nginx/ingress-nginx
    version: 4.13.0
    createNamespace: true
    wait: true
    atomic: true
    values:
      - values/nginx.yaml.gotmpl
