repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-operator
    namespace: prometheus-operator
    chart: prometheus-community/kube-prometheus-stack
    version: 75.15.0
    createNamespace: true
    wait: true
    atomic: true
    values:
      - values/prometheus.yaml.gotmpl
