name: Test Helmfiles

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  validate:
    runs-on: r2dlan-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm + Helmfile
        uses: azure/setup-helm@v3
        with:
          version: "v3.12.0"

      - name: Install helmfile
        run: |
          curl -L https://github.com/helmfile/helmfile/releases/download/v1.1.3/helmfile_1.1.3_linux_arm64.tar.gz | tar xz
          sudo mv helmfile /usr/local/bin

      - name: Helmfile lint
        run: |
          find charts/ -name helmfile.yaml -execdir helmfile lint \;
