name: Autoupdate Helmfiles

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  update:
    runs-on: r2dlan-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm + Helmfile
        uses: azure/setup-helm@v3
        with:
          version: "v3.12.0"

      - name: Install helmfile
        run: |
          curl -L https://github.com/helmfile/helmfile/releases/download/v1.1.3/helmfile_1.1.3_linux_arm64.tar.gz | tar xz
          sudo mv helmfile /usr/local/bin

      - name: Update application
        run: |
          for chart in $(git diff --name-only HEAD^ HEAD | grep '^charts/' | cut -d '/' -f1-2 | sort -u)
          do
            echo "\nUpdate helm Chart ${chart}"
            helmfile apply -f ${chart}
            echo "\n"
          done
